-- ==========================================
-- FUZO Food Discovery - Core Schema
-- ==========================================

-- Enable the "pg_trgm" extension for text search if needed later
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 1. PROFILES TABLE (Extends auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  food_dna JSONB DEFAULT '{}'::jsonb, -- Stores flavor weights and dietary preferences
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Trigger to create profile automatically on auth.users insert
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop trigger if exists to allow safe re-runs
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 2. RECIPES TABLE (For curatedRecipes.json)
CREATE TABLE IF NOT EXISTS public.recipes (
  id BIGINT PRIMARY KEY, -- Using the exact ID from JSON
  title TEXT NOT NULL,
  image TEXT,
  ready_in_minutes INT,
  servings INT,
  diets TEXT[] DEFAULT '{}',
  dish_types TEXT[] DEFAULT '{}',
  cuisines TEXT[] DEFAULT '{}',
  flavor_profile JSONB DEFAULT '{}'::jsonb,
  ingredients JSONB DEFAULT '[]'::jsonb,
  instructions TEXT,
  analyzed_instructions JSONB DEFAULT '[]'::jsonb,
  nutrition JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);


-- 3. USER INTERACTIONS TABLE (For Recommendation Engine tracking)
CREATE TABLE IF NOT EXISTS public.user_interactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  recipe_id BIGINT REFERENCES public.recipes(id) ON DELETE CASCADE,
  interaction_type TEXT CHECK (interaction_type IN ('view', 'like', 'save', 'skip')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, recipe_id, interaction_type)
);

-- Index for fast interaction lookups
CREATE INDEX IF NOT EXISTS idx_user_interactions_user_id ON public.user_interactions(user_id);


-- 4. RECOMMENDATION ENGINE RPC
-- Calculates distance between user's Food DNA and Recipe's flavor profile.
-- The formula calculates euclidean distance between the 10 flavor axes.
CREATE OR REPLACE FUNCTION public.get_recommended_recipes(
  p_user_id UUID, 
  p_limit INT DEFAULT 10,
  p_offset INT DEFAULT 0
)
RETURNS TABLE (
  recipe_id BIGINT,
  title TEXT,
  image TEXT,
  ready_in_minutes INT,
  servings INT,
  diets TEXT[],
  flavor_profile JSONB,
  match_score FLOAT
) AS $$
DECLARE
  v_user_dna JSONB;
BEGIN
  -- Get user's Food DNA
  SELECT food_dna INTO v_user_dna FROM public.profiles WHERE id = p_user_id;

  -- If user has no Food DNA setup, return random/latest recipes (fallback)
  IF v_user_dna IS NULL OR v_user_dna = '{}'::jsonb THEN
    RETURN QUERY
    SELECT r.id, r.title, r.image, r.ready_in_minutes, r.servings, r.diets, r.flavor_profile, 0.0::FLOAT AS match_score
    FROM public.recipes r
    WHERE r.id NOT IN (
      SELECT ui.recipe_id FROM public.user_interactions ui WHERE ui.user_id = p_user_id AND ui.interaction_type IN ('skip', 'like', 'save')
    )
    ORDER BY RANDOM()
    LIMIT p_limit OFFSET p_offset;
    RETURN;
  END IF;

  -- Otherwise, calculate match based on flavor profiles
  -- We assume v_user_dna and flavor_profile both contain keys: spicy, sweet, tangy, salty, savory, bitter, smoky, creamy, fresh, crunchy
  -- Values are 0.0 to 5.0 (or similar scale). Lower distance = higher match score.
  RETURN QUERY
  SELECT 
    r.id, 
    r.title, 
    r.image, 
    r.ready_in_minutes, 
    r.servings, 
    r.diets,
    r.flavor_profile,
    (
      -- Calculate Euclidean Distance
      SQRT(
        POWER(COALESCE((r.flavor_profile->>'spicy')::FLOAT, 0) - COALESCE((v_user_dna->>'spicy')::FLOAT, 0), 2) +
        POWER(COALESCE((r.flavor_profile->>'sweet')::FLOAT, 0) - COALESCE((v_user_dna->>'sweet')::FLOAT, 0), 2) +
        POWER(COALESCE((r.flavor_profile->>'tangy')::FLOAT, 0) - COALESCE((v_user_dna->>'tangy')::FLOAT, 0), 2) +
        POWER(COALESCE((r.flavor_profile->>'salty')::FLOAT, 0) - COALESCE((v_user_dna->>'salty')::FLOAT, 0), 2) +
        POWER(COALESCE((r.flavor_profile->>'savory')::FLOAT, 0) - COALESCE((v_user_dna->>'savory')::FLOAT, 0), 2) +
        POWER(COALESCE((r.flavor_profile->>'bitter')::FLOAT, 0) - COALESCE((v_user_dna->>'bitter')::FLOAT, 0), 2) +
        POWER(COALESCE((r.flavor_profile->>'smoky')::FLOAT, 0) - COALESCE((v_user_dna->>'smoky')::FLOAT, 0), 2) +
        POWER(COALESCE((r.flavor_profile->>'creamy')::FLOAT, 0) - COALESCE((v_user_dna->>'creamy')::FLOAT, 0), 2) +
        POWER(COALESCE((r.flavor_profile->>'fresh')::FLOAT, 0) - COALESCE((v_user_dna->>'fresh')::FLOAT, 0), 2) +
        POWER(COALESCE((r.flavor_profile->>'crunchy')::FLOAT, 0) - COALESCE((v_user_dna->>'crunchy')::FLOAT, 0), 2)
      )
    ) AS match_score
  FROM public.recipes r
  WHERE r.id NOT IN (
    -- Exclude recipes the user has already interacted with (swiped away or saved)
    SELECT ui.recipe_id FROM public.user_interactions ui WHERE ui.user_id = p_user_id AND ui.interaction_type IN ('skip', 'like', 'save')
  )
  -- Order by distance ASC (lowest distance = highest match)
  ORDER BY match_score ASC
  LIMIT p_limit OFFSET p_offset;
END;
$$ LANGUAGE plpgsql;


-- ==========================================
-- ROW LEVEL SECURITY (RLS)
-- ==========================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_interactions ENABLE ROW LEVEL SECURITY;

-- Profiles: Users can read and update their own profile. Others can read public info (if needed).
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Recipes: Anyone can read, only service role can insert/update (via script).
CREATE POLICY "Recipes are viewable by everyone." ON public.recipes FOR SELECT USING (true);
-- No insert/update policies because we use the Service Role key in the seed script which bypasses RLS.

-- User Interactions: Users can only see and create their own interactions.
CREATE POLICY "Users can view own interactions." ON public.user_interactions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own interactions." ON public.user_interactions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own interactions." ON public.user_interactions FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own interactions." ON public.user_interactions FOR DELETE USING (auth.uid() = user_id);
