#!/usr/bin/env node

/**
 * FUZO AI Setup Script
 *
 * This script helps you set up the AI functionality for FUZO.
 * It will guide you through configuring the OpenAI API key and other necessary settings.
 */

import fs from "fs";
import path from "path";
import readline from "readline";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function main() {
  console.log("🐙 FUZO AI Setup Script");
  console.log("========================\n");

  console.log(
    "This script will help you configure the AI functionality for FUZO."
  );
  console.log("You'll need an OpenAI API key to enable the AI assistant.\n");

  // Check if .env file exists
  const envPath = path.join(process.cwd(), ".env");
  const envExists = fs.existsSync(envPath);

  if (envExists) {
    console.log("✅ Found existing .env file");
    const overwrite = await question(
      "Do you want to update the existing .env file? (y/N): "
    );
    if (overwrite.toLowerCase() !== "y" && overwrite.toLowerCase() !== "yes") {
      console.log("Setup cancelled.");
      rl.close();
      return;
    }
  }

  console.log("\n📝 Environment Configuration");
  console.log("============================\n");

  // Get OpenAI API key
  const openaiKey = await question(
    "Enter your OpenAI API key (or press Enter to skip): "
  );

  // Get other optional keys
  const googleMapsKey = await question(
    "Enter your Google Maps API key (optional): "
  );
  const supabaseUrl = await question("Enter your Supabase URL (optional): ");
  const supabaseAnonKey = await question(
    "Enter your Supabase Anon Key (optional): "
  );

  // Create .env content
  let envContent = `# FUZO Environment Configuration
# Generated by setup-ai.js on ${new Date().toISOString()}
#
# SECURITY NOTE: Never expose API keys to the client-side!
# Only server-side environment variables are used for AI functionality.

# AI Services (Server-side only - REQUIRED for AI Assistant)
OPENAI_API_KEY=${openaiKey || "your_openai_api_key_here"}

# Google Services (Server-side for backend, client-side for frontend)
GOOGLE_MAPS_API_KEY=${googleMapsKey || "your_google_maps_api_key_here"}
GOOGLE_CLIENT_ID=your_google_client_id_here
GOOGLE_CLIENT_SECRET=your_google_client_secret_here

# Supabase (Server-side for backend, client-side for frontend)
SUPABASE_URL=${supabaseUrl || "your_supabase_url_here"}
SUPABASE_ANON_KEY=${supabaseAnonKey || "your_supabase_anon_key_here"}
SUPABASE_SERVICE_ROLE_KEY=your_supabase_service_role_key_here

# Stream Chat (Server-side for backend, client-side for frontend)
STREAM_API_KEY=your_stream_api_key_here
STREAM_SECRET=your_stream_secret_here
STREAM_WEBHOOK_SECRET=your_webhook_secret_here

# Food Services (Server-side only)
SPOONACULAR_API_KEY=your_spoonacular_api_key_here

# Development
NODE_ENV=development
VITE_APP_ENV=development

# Vite Environment Variables (Client-side safe - prefixed with VITE_)
# These are safe to expose to the client
VITE_SUPABASE_URL=\${SUPABASE_URL}
VITE_SUPABASE_ANON_KEY=\${SUPABASE_ANON_KEY}
VITE_GOOGLE_MAPS_API_KEY=\${GOOGLE_MAPS_API_KEY}
VITE_STREAM_CHAT_API_KEY=\${STREAM_API_KEY}

# IMPORTANT: DO NOT add VITE_OPENAI_API_KEY here!
# OpenAI API key should NEVER be exposed to the client-side for security reasons.
`;

  // Write .env file
  try {
    fs.writeFileSync(envPath, envContent);
    console.log("\n✅ .env file created successfully!");
  } catch (error) {
    console.error("\n❌ Error creating .env file:", error.message);
    rl.close();
    return;
  }

  // Test AI configuration
  if (openaiKey && openaiKey !== "your_openai_api_key_here") {
    console.log("\n🧪 Testing AI Configuration...");
    console.log("=============================");

    // Set environment variable for testing
    process.env.OPENAI_API_KEY = openaiKey;

    try {
      // Try to import and test the AI configuration
      const { getAIConfig, isAIConfigured } = await import(
        "./lib/ai-config.js"
      );
      const config = getAIConfig();
      const configured = isAIConfigured();

      if (configured) {
        console.log("✅ AI configuration is valid!");
        console.log(`   Provider: OpenAI`);
        console.log(`   Model: ${config.openai.model}`);
      } else {
        console.log("❌ AI configuration failed. Please check your API key.");
      }
    } catch (error) {
      console.log("⚠️  Could not test AI configuration:", error.message);
      console.log(
        "   This might be normal if dependencies are not installed yet."
      );
    }
  } else {
    console.log(
      "\n⚠️  No OpenAI API key provided. AI functionality will use fallback responses."
    );
    console.log(
      "   To enable full AI functionality, run this script again with a valid API key."
    );
  }

  console.log("\n🎉 Setup Complete!");
  console.log("==================");
  console.log("Next steps:");
  console.log("1. Install dependencies: npm install");
  console.log("2. Start the development server: npm run dev");
  console.log("3. Test the AI assistant by clicking the Tako button");
  console.log('4. Use "Test AI Connection" to verify everything is working');

  if (!openaiKey || openaiKey === "your_openai_api_key_here") {
    console.log("\n💡 To get an OpenAI API key:");
    console.log("   1. Go to https://platform.openai.com/api-keys");
    console.log("   2. Create a new API key");
    console.log("   3. Run this script again with your key");
  }

  rl.close();
}

main().catch(console.error);
